from src.domain.entities.compliance import ComplianceCriterion

CRITERIA: list[ComplianceCriterion] = [
    ComplianceCriterion(
        id="backend/dod/lint-clean",
        guideline_slug="agile/05-dod-backend",
        stack="backend",
        text="Lint clean — ruff check exits 0, no unapproved noqa suppressions",
        category="code-quality",
        severity="required",
        check_type="command",
        verification_hint="Run `ruff check .` and paste the full output (stdout + stderr)",
        check_command="ruff check .",
        pass_pattern=r"All checks passed",
        fail_pattern=r"\d+\s+error|Found \d+",
    ),
    ComplianceCriterion(
        id="backend/dod/format-clean",
        guideline_slug="agile/05-dod-backend",
        stack="backend",
        text="Format clean — ruff format --check exits 0",
        category="code-quality",
        severity="required",
        check_type="command",
        verification_hint="Run `ruff format --check .` and paste the full output",
        check_command="ruff format --check .",
        pass_pattern=r"files? already formatted",
        fail_pattern=r"would reformat|\d+ files? would be reformatted",
    ),
    ComplianceCriterion(
        id="backend/dod/type-check-clean",
        guideline_slug="agile/05-dod-backend",
        stack="backend",
        text="Type-check clean — mypy --strict exits 0, no new type: ignore added without justification",
        category="code-quality",
        severity="required",
        check_type="command",
        verification_hint="Run `uv run mypy --strict src/` and paste the full output",
        check_command="uv run mypy --strict src/",
        pass_pattern=r"Success: no issues found",
        fail_pattern=r"error:|Found \d+ error",
    ),
    ComplianceCriterion(
        id="backend/dod/unit-tests-green",
        guideline_slug="agile/05-dod-backend",
        stack="backend",
        text="Unit tests green — every new use-case has at least one test; every branch is covered",
        category="testing",
        severity="required",
        check_type="command",
        verification_hint="Run `pytest` and paste the full output",
        check_command="pytest",
        pass_pattern=r"\d+ passed",
        fail_pattern=r"FAILED|ERROR|\d+ failed",
    ),
    ComplianceCriterion(
        id="backend/dod/coverage-met",
        guideline_slug="agile/05-dod-backend",
        stack="backend",
        text="Coverage meets the project threshold (commonly 80%+)",
        category="testing",
        severity="required",
        check_type="command",
        verification_hint="Run `pytest --cov=src --cov-report=term-missing` and paste the TOTAL line",
        check_command="pytest --cov=src --cov-report=term-missing",
        pass_pattern=r"TOTAL\s+\d+\s+\d+\s+([89]\d|100)%",
        fail_pattern=r"TOTAL\s+\d+\s+\d+\s+[0-7]\d%",
    ),
    ComplianceCriterion(
        id="backend/dod/complexity-cap",
        guideline_slug="agile/05-dod-backend",
        stack="backend",
        text="Cyclomatic complexity ≤ 10 for every new function (ruff C90)",
        category="code-quality",
        severity="required",
        check_type="command",
        verification_hint="Run `ruff check . --select C90` and paste the full output",
        check_command="ruff check . --select C90",
        pass_pattern=r"All checks passed",
        fail_pattern=r"C901|too complex",
    ),
    ComplianceCriterion(
        id="backend/dod/auth-on-routes",
        guideline_slug="agile/05-dod-backend",
        stack="backend",
        text="Every new route is guarded by an authorization dependency",
        category="security",
        severity="required",
        check_type="code_pattern",
        verification_hint="Paste the FastAPI route handler(s) introduced by the slice",
        required_pattern=r"Depends\s*\(\s*require|@require\s*\(",
    ),
    ComplianceCriterion(
        id="backend/dod/audit-on-write",
        guideline_slug="agile/05-dod-backend",
        stack="backend",
        text="Every write path emits a structured audit event in the same transaction",
        category="security",
        severity="required",
        check_type="code_pattern",
        verification_hint="Paste the use-case execute() method for each write operation in the slice",
        required_pattern=r"audit_event\s*\(|emit_audit\s*\(|AuditEvent\s*\(|audit\.log\s*\(",
    ),
    ComplianceCriterion(
        id="backend/dod/integration-testcontainers",
        guideline_slug="agile/05-dod-backend",
        stack="backend",
        text="Integration tests use testcontainers (not a mocked DB)",
        category="testing",
        severity="required",
        check_type="manual",
        verification_hint="Provide the conftest.py path and the fixture name that sets up the real DB container",
    ),
]
