from src.domain.entities.compliance import ComplianceCriterion

CRITERIA: list[ComplianceCriterion] = [
    ComplianceCriterion(
        id="frontend/dod/lint-clean",
        guideline_slug="agile/06-dod-frontend",
        stack="frontend",
        text="Lint clean — eslint exits 0",
        category="code-quality",
        severity="required",
        check_type="command",
        verification_hint="Run `eslint .` (or `npx eslint .`) and paste the full output",
        check_command="eslint .",
        pass_pattern=r"^\s*$",
        fail_pattern=r"error\s+.+\s+\w+/\w+|\d+ error",
    ),
    ComplianceCriterion(
        id="frontend/dod/format-clean",
        guideline_slug="agile/06-dod-frontend",
        stack="frontend",
        text="Format clean — prettier --check exits 0",
        category="code-quality",
        severity="required",
        check_type="command",
        verification_hint="Run `npx prettier --check .` and paste the full output",
        check_command="npx prettier --check .",
        pass_pattern=r"All matched files use Prettier formatting|unchanged",
        fail_pattern=r"Code style issues found",
    ),
    ComplianceCriterion(
        id="frontend/dod/type-check-clean",
        guideline_slug="agile/06-dod-frontend",
        stack="frontend",
        text="Type-check clean — tsc --noEmit exits 0, no `any` introduced",
        category="code-quality",
        severity="required",
        check_type="command",
        verification_hint="Run `npx tsc --noEmit` and paste the full output",
        check_command="npx tsc --noEmit",
        pass_pattern=r"^\s*$",
        fail_pattern=r"error TS\d+|\.tsx?\(\d+",
    ),
    ComplianceCriterion(
        id="frontend/dod/no-any",
        guideline_slug="agile/06-dod-frontend",
        stack="frontend",
        text="No new `any` type annotation introduced in TypeScript files",
        category="code-quality",
        severity="required",
        check_type="code_pattern",
        verification_hint="Paste the TypeScript files changed in this slice",
        forbidden_pattern=r":\s*any\b|as\s+any\b|<any>",
    ),
    ComplianceCriterion(
        id="frontend/dod/unit-tests-green",
        guideline_slug="agile/06-dod-frontend",
        stack="frontend",
        text="Unit tests green — vitest passes; new hooks/components have at least one test",
        category="testing",
        severity="required",
        check_type="command",
        verification_hint="Run `npx vitest run` and paste the full output",
        check_command="npx vitest run",
        pass_pattern=r"Tests\s+\d+ passed|\d+ passed",
        fail_pattern=r"FAIL|failed\s+\d+|\d+ failed",
    ),
    ComplianceCriterion(
        id="frontend/dod/e2e-green",
        guideline_slug="agile/06-dod-frontend",
        stack="frontend",
        text="Playwright E2E green for the affected critical flow",
        category="testing",
        severity="required",
        check_type="command",
        verification_hint="Run `npx playwright test` and paste the summary output",
        check_command="npx playwright test",
        pass_pattern=r"\d+ passed",
        fail_pattern=r"\d+ failed|Error:",
    ),
]
