# Description: Domain entity — ORM-mapped class that owns its business logic
# Layer: domain
#
# Key rules:
#   - ID is generated by the entity, never passed in from outside
#   - Password is ALWAYS hashed on write; plain text never stored
#   - Business logic (verify_password) lives HERE, not in a service or route
#   - No HTTP imports, no use-case imports — pure domain code

from __future__ import annotations

import bcrypt
from snowflake import SnowflakeGenerator
from sqlalchemy import String
from sqlalchemy.orm import Mapped, mapped_column

from src.infrastructure.db.base import Base  # declarative base — only allowed DB import

_id_gen = SnowflakeGenerator(42)


class User(Base):
    __tablename__ = "users"

    # ID is owned by the entity — callers never supply it
    id: Mapped[int] = mapped_column(primary_key=True, default=lambda: next(_id_gen))
    email: Mapped[str] = mapped_column(String(254), unique=True, nullable=False)
    # Column is private; access only via property
    _password_hash: Mapped[str] = mapped_column("password_hash", String(72), nullable=False)

    # --- business logic ---------------------------------------------------

    @property
    def password(self) -> str:
        raise AttributeError("Password is write-only.")

    @password.setter
    def password(self, plain: str) -> None:
        self._password_hash = bcrypt.hashpw(plain.encode(), bcrypt.gensalt()).decode()

    def verify_password(self, plain: str) -> bool:
        return bcrypt.checkpw(plain.encode(), self._password_hash.encode())

    # --- test helper ------------------------------------------------------

    @staticmethod
    def _mock(email: str = "test@example.com", password: str = "secret") -> "User":
        u = User(email=email)
        u.password = password
        return u


# =============================================================================
# ANTI-PATTERN — do NOT do this
# =============================================================================

class UserBad:
    def __init__(self, id, email, password):
        self.id = id
        self.email = email
        self.password = password         # plain text stored — catastrophic leak risk

    # verify_password lives in a route handler or service — duplicated everywhere
